name: Move PR to Done on merge to main

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  pull-requests: read
  contents: read
  repository-projects: write

jobs:
  move-to-done:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Move PR to Done
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PROJECT_TOKEN }}
          script: |
            const PROJECT_NUMBER = 1;
            const OWNER = "libertadores-talleres";
            const STATUS_FIELD_NAME = 'Status';
            const TARGET_STATUS = 'Done';
            
            console.log('PR mergeado:', context.payload.pull_request.number);
            console.log('Título:', context.payload.pull_request.title);
            
            try {
              // 1️⃣ Obtener el Project ID y opciones del campo Status
              const projectQuery = `
                query($owner: String!, $number: Int!, $fieldName: String!) {
                  organization(login: $owner) {
                    projectV2(number: $number) {
                      id
                      field(name: $fieldName) {
                        ... on ProjectV2SingleSelectField {
                          id
                          options { id name }
                        }
                      }
                    }
                  }
                }
              `;
              
              const projectData = await github.graphql(projectQuery, {
                owner: OWNER,
                number: PROJECT_NUMBER,
                fieldName: STATUS_FIELD_NAME
              });
              
              const project = projectData.organization?.projectV2;
              if (!project) {
                console.log('❌ No se encontró el proyecto');
                return;
              }
              
              console.log('✅ Project ID:', project.id);
              
              // 2️⃣ Buscar la opción "Done"
              const statusField = project.field;
              const statusOption = statusField.options.find(opt => opt.name === TARGET_STATUS);
              
              if (!statusOption) {
                console.log(`❌ No se encontró el estado "${TARGET_STATUS}"`);
                console.log('Estados disponibles:', statusField.options.map(o => o.name));
                return;
              }
              
              console.log('✅ Status Option ID:', statusOption.id);
              
              // 3️⃣ Buscar si el PR ya está en el proyecto
              const itemQuery = `
                query($prId: ID!) {
                  node(id: $prId) {
                    ... on PullRequest {
                      projectItems(first: 10) {
                        nodes { id project { id } }
                      }
                    }
                  }
                }
              `;
              
              const prData = await github.graphql(itemQuery, {
                prId: context.payload.pull_request.node_id
              });
              
              let projectItem = prData.node.projectItems.nodes.find(
                item => item.project.id === project.id
              );
              
              let itemId;
              if (!projectItem) {
                console.log('⚙️ El PR no está en el proyecto. Agregándolo...');
                
                const addItemMutation = `
                  mutation($projectId: ID!, $contentId: ID!) {
                    addProjectV2ItemById(input: {projectId: $projectId, contentId: $contentId}) {
                      item { id }
                    }
                  }
                `;
                
                const addResult = await github.graphql(addItemMutation, {
                  projectId: project.id,
                  contentId: context.payload.pull_request.node_id
                });
                
                itemId = addResult.addProjectV2ItemById.item.id;
                console.log('✅ PR agregado al proyecto. Item ID:', itemId);
              } else {
                itemId = projectItem.id;
                console.log('✅ Item ID encontrado:', itemId);
              }
              
              // 4️⃣ Actualizar el campo Status a "Done"
              const updateMutation = `
                mutation($projectId: ID!, $itemId: ID!, $fieldId: ID!, $optionId: String!) {
                  updateProjectV2ItemFieldValue(
                    input: {
                      projectId: $projectId
                      itemId: $itemId
                      fieldId: $fieldId
                      value: { singleSelectOptionId: $optionId }
                    }
                  ) { projectV2Item { id } }
                }
              `;
              
              await github.graphql(updateMutation, {
                projectId: project.id,
                itemId: itemId,
                fieldId: statusField.id,
                optionId: statusOption.id
              });
              
              console.log(`🎉 PR #${context.payload.pull_request.number} movido a "${TARGET_STATUS}"`);
              
            } catch (error) {
              console.error('❌ Error:', error);
              core.setFailed(error.message);
            }
